import 'package:hive_flutter/hive_flutter.dart';
import '../models/menu_item.dart';

class StorageService {
  static const String _menuItemsBox = 'menu_items';
  Box<MenuItem>? _box;

  Future<void> init() async {
    await Hive.initFlutter();
    // Hive adapters will be generated by hive_generator
    // For now, we'll register them manually in main
    _box = await Hive.openBox<MenuItem>(_menuItemsBox);
  }

  Future<void> saveMenuItem(MenuItem item) async {
    await _box?.put(item.id, item);
  }

  Future<void> saveMenuItems(List<MenuItem> items) async {
    for (final item in items) {
      await saveMenuItem(item);
    }
  }

  Future<MenuItem?> getMenuItem(String id) async {
    return _box?.get(id);
  }

  List<MenuItem> getAllMenuItems() {
    return _box?.values.toList() ?? [];
  }

  Future<void> deleteMenuItem(String id) async {
    await _box?.delete(id);
  }

  Future<void> clear() async {
    await _box?.clear();
  }
}
